baseURL = 'https://oscilador.com/'
languageCode = 'en-us'
title = 'oscilador'

theme = "hugo-blog-awesome"

[[params.socialIcons]]
name = "github"
url = "https://github.com/eloscilador"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/el_oscilador"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"
